#! /bin/bash

## add an NX user remotely
## usage:
## NXadduser username 

if [ "$NXset" != "set" ]; then
    source $NXDIR/NXsetup
fi

## add user
ssh $DSKaccount "echo -e '$2\n$2' | sudo /usr/NX/bin/nxserver --system --useradd $1"

## make .nxs session file
sed -e "s/ABQUSER/$1/g" -e "s/ABQDSK/$DSKmachine/g" $NXDIR/sessions/AWSdesktop.nxs-generic > $NXDIR/sessions/AWSdesktop.nxs-$1

## link it properly
ln -fs $NXDIR/sessions/AWSdesktop.nxs-$1 $SESSIONDIR/AWSdesktop.nxs
