#! /bin/bash

## set up the machines and keys

export NXDIR=$PWD 
#export DSKmachine=ec2-50-18-130-102.us-west-1.compute.amazonaws.com 
export DSKmachine=ec2-54-215-98-211.us-west-1.compute.amazonaws.com
#export DSKmachine=ec2-54-215-66-32.us-west-1.compute.amazonaws.com 
export DSKaccount=ubuntu@$DSKmachine 
export DSKkey=$NXDIR/keys/AWS_desktop_hosts.pem

#export DSKmachine=192.168.1.72 
#export DSKaccount=khalighi@$DSKmachine 
#export DSKkey=$NXDIR/keys/VM_desktop_hosts.pem

export WEBmachine=ec2-54-241-70-19.us-west-1.compute.amazonaws.com 
export WEBaccount=ubuntu@$WEBmachine 
export WEBkey=$NXDIR/keys/AWS_webserver_hosts.pem
export SESSIONDIR=/home/khalighi/.nx/config/

export NXset=set 

