#! /bin/bash

## this routine connects to a machine and runs a script
## usage
## runSSH script machinename

echo "copying $1"
scp -o "StrictHostKeyChecking no" $1 $2:/tmp > /dev/null 2>&1
echo "executing $1"
ssh -o "StrictHostKeyChecking no" $2 "/tmp/$1; rm -f /tmp/$1"
